### ISSUE TITLE
Brain Behavior

### ISSUE THREAD

**Issue by EliCDavis** [EliCDavis/Pathogen#10]
The brain should ultimately control the spawning of the cells inside of the boss fight based on the kind of damage it is taking and in what area it is taking it.

The brain is sectioned out into parts which can be destroyed one at a time, each making the brain more aggressive.  So each part needs to keep up with it's own health and have some way of indicating that it's been taken out.

When the brain has been officially taken out a cut scene should play and the end credits should play.

**Comment by DakotaHall5** [comment]
So is the spawning of the enemies going to be based on percentages of damage dealt, or is it going to be caused by the destruction of pieces? Possibly both?

**Comment by EliCDavis** [comment]
I would def do both.   Rate of spawn is inverse function of brain health, and a wave comes out each destruction of a brain piece.

**Comment by DakotaHall5** [comment]
Should each brain piece have a different amount of health or a uniform amount of health for all? Some pieces are significantly smaller than the rest, so I figured they would have less health.
